[package]
name = "test_game"
version = "0.1.0"
edition = "2021"

[dependencies]
crossterm = "0.27.0"
ratatui = "0.27.0"
serde = { version = "1.0.204", features = ["derive"] }
server = { version = "0.1.0", path = "../server" }
